name: vpn_server
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push:
    name: Build and Push Go Server Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check login
        run: docker info

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          provenance: false
          tags: |
            neimes/vpnbot_server:latest
            neimes/vpnbot_server:${{ github.sha }}
          cache-from: type=registry,ref=neimes/vpnbot_server:latest
          cache-to: type=inline